import Head from "next/head";
// import Image from "next/image";
// import styles from "@/styles/Home.module.css";
import Banner from "../components/banner/banner";
import NavBar from "@/components/nav/navbar";
import Card from "@/components/card/card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pixy Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Pixy Box</h1> */}
      <NavBar username="deayan252@gmail.com" />
      <Banner
        title="Panther Panchali"
        subTitle="First Apu Triology"
        imgUrl="./static/rajnikant.jpg"
      />
      <Card imgUrl="/static/animal.jpg" size="large" />
      <Card imgUrl="/static/animal.jpg" size="medium" />
      <Card imgUrl="/static/animal.jpg" size="small" />
    </>
  );
}
