import Head from "next/head";
// import Image from "next/image";
// import styles from "@/styles/Home.module.css";
import Banner from "../components/banner/banner";
import NavBar from "@/components/nav/navbar";
import SectionCards from "@/components/card/section-card";
import { getVideos } from "../lib/videos";
// type HomeProps ={
//   animeVideos
// }

//implementing server side rendering
export async function getServerSideProps(context) {
  const animeVideos = await getVideos("disney trailer");
  const youHaveWatchedVideos = await getVideos("Bollywood trailer");
  const ourRecommendMovies = await getVideos("indian music");
  return {
    props: { animeVideos, ourRecommendMovies, youHaveWatchedVideos }, // will be passed to the page component as props
  };
}

export default function Home({
  animeVideos,
  ourRecommendMovies,
  youHaveWatchedVideos,
}) {
  return (
    <>
      <Head>
        <title>Pixy Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Pixy Box</h1> */}
      <NavBar />
      <Banner
        title="Panther Panchali"
        subTitle="First Apu Triology"
        imgUrl="./static/rajnikant.jpg"
        videoId="pSnMt6h6zk0"
      />
      <SectionCards title="Top this weeks" videos={animeVideos} size="large" />
      <SectionCards
        title="Recommendations"
        videos={ourRecommendMovies}
        size="medium"
      />
      <SectionCards
        title="You Have Watched"
        videos={youHaveWatchedVideos}
        size="small"
      />
    </>
  );
}
